
-- Consulta 1: Obtener el supermercado que tenga más cantidad de productos "CARNICOS" vendidos hasta el 31 de diciembre de 2013.
SELECT 
    S.NOMBRE_SUPERMERCADO, 
    SUM(F.CANTIDAD) AS TOTAL_CARNICOS, 
    P.DESCRIPCION_PRODUCTO, 
    F.FECHA_VENTA
FROM FACTURA F
JOIN PRODUCTO P ON F.ID_PRODUCTO = P.ID_PRODUCTO
JOIN SUPERMERCADO S ON S.ID_SUPERMERCADO = (SELECT V.ID_SUPERMERCADO FROM VENDEDOR V WHERE V.ID_VENDEDOR = F.ID_VENDEDOR)
WHERE 
    P.DESCRIPCION_PRODUCTO LIKE '%CARNICOS%' 
    AND F.FECHA_VENTA <= '2013-12-31'
GROUP BY 
    S.NOMBRE_SUPERMERCADO, P.DESCRIPCION_PRODUCTO, F.FECHA_VENTA
ORDER BY 
    TOTAL_CARNICOS DESC
LIMIT 1;


-- Consulta 2: Seleccionar los clientes que compran en el SUPERMERCADO "Exito" cuyas compras superen $150,000.
SELECT 
    C.*, 
    S.NOMBRE_SUPERMERCADO, 
    F.VALOR_VENTA
FROM CLIENTE C
JOIN FACTURA F ON C.ID_CLIENTE = F.ID_CLIENTE
JOIN  VENDEDOR V ON F.ID_VENDEDOR = V.ID_VENDEDOR
JOIN UPERMERCADO S ON V.ID_SUPERMERCADO = S.ID_SUPERMERCADO
WHERE S.NOMBRE_SUPERMERCADO = 'Exito' AND F.VALOR_VENTA > 150000
ORDER BY 
F.VALOR_VENTA DESC;
